export type Language = "en" | "mr" | "hi";

export const strings = {
  en: {
    appName: "PFAAI",
    splashGreeting: "Hi! 👋 I am your Personal Best Friend",
    selectLanguage: "Choose your language",
    setupTitle: "Let's set up!",
    yourName: "Your name",
    yourNamePlaceholder: "What should I call you?",
    aiName: "My name",
    aiNamePlaceholder: "Give me a nickname...",
    voiceType: "My voice type",
    voiceMale: "Male",
    voiceFemale: "Female",
    voiceChild: "Child",
    next: "Let's Go!",
    typeMessage: "Type a message...",
    voiceMode: "Voice",
    chatMode: "Chat",
    listening: "Listening...",
    processing: "Thinking...",
    send: "Send",
    settings: "Settings",
    clearChat: "Clear Chat",
    changeLanguage: "Language",
    changeVoice: "Voice Type",
    wakeWord: "Wake Word",
    resetApp: "Reset App",
    close: "Close",
    cancel: "Cancel",
    wakeWordHint: "Say this to wake me up",
    welcomeMessage:
      "Hi! 👋 I'm your personal best friend! Talk to me about anything.\n\n💡 You can:\n• Ask me math questions\n• Tell me to 'remember that...'\n• Teach me: 'when I say X, say Y'\n• Ask for the time or date",
    voiceHint: "Tap mic to speak",
    wakeWordNote:
      "⚡ Wake word works on installed APK. In Expo Go, use the mic button.",
    confirmReset: "Are you sure? This will erase everything.",
    yes: "Yes, Reset",
    no: "No",
  },
  mr: {
    appName: "PFAAI",
    splashGreeting: "हाय! 👋 मी तुमचा खास मित्र आहे",
    selectLanguage: "भाषा निवडा",
    setupTitle: "चला सुरुवात करूया!",
    yourName: "तुमचे नाव",
    yourNamePlaceholder: "मी तुम्हाला काय म्हणू?",
    aiName: "माझे नाव",
    aiNamePlaceholder: "मला एक नाव द्या...",
    voiceType: "माझा आवाज",
    voiceMale: "पुरुष",
    voiceFemale: "महिला",
    voiceChild: "मुलगा/मुलगी",
    next: "चला सुरू करूया!",
    typeMessage: "संदेश टाइप करा...",
    voiceMode: "आवाज",
    chatMode: "चॅट",
    listening: "ऐकतोय...",
    processing: "विचार करतोय...",
    send: "पाठवा",
    settings: "सेटिंग्ज",
    clearChat: "चॅट साफ करा",
    changeLanguage: "भाषा",
    changeVoice: "आवाज",
    wakeWord: "वेक वर्ड",
    resetApp: "App रीसेट करा",
    close: "बंद",
    cancel: "रद्द करा",
    wakeWordHint: "हे म्हणाल तर मी जागा होईन",
    welcomeMessage:
      "नमस्ते! 👋 मी तुमचा खास मित्र आहे! कोणत्याही गोष्टीबद्दल बोला.\n\n💡 तुम्ही करू शकता:\n• गणिताचे प्रश्न विचारा\n• 'लक्षात ठेव की...' सांगा\n• शिकवा: 'जेव्हा मी X म्हणतो, तेव्हा Y म्हण'\n• वेळ किंवा तारीख विचारा",
    voiceHint: "बोलण्यासाठी mic दाबा",
    wakeWordNote:
      "⚡ APK install केल्यावर wake word काम करेल. Expo Go मध्ये mic button वापरा.",
    confirmReset: "खात्री आहे का? सगळं मिटेल.",
    yes: "हो, रीसेट करा",
    no: "नाही",
  },
  hi: {
    appName: "PFAAI",
    splashGreeting: "नमस्ते! 👋 मैं आपका खास दोस्त हूँ",
    selectLanguage: "भाषा चुनें",
    setupTitle: "चलिए शुरू करते हैं!",
    yourName: "आपका नाम",
    yourNamePlaceholder: "मैं आपको क्या बुलाऊं?",
    aiName: "मेरा नाम",
    aiNamePlaceholder: "मुझे एक नाम दें...",
    voiceType: "मेरी आवाज",
    voiceMale: "पुरुष",
    voiceFemale: "महिला",
    voiceChild: "बच्चा",
    next: "चलिए शुरू करें!",
    typeMessage: "संदेश टाइप करें...",
    voiceMode: "आवाज",
    chatMode: "चैट",
    listening: "सुन रहा हूँ...",
    processing: "सोच रहा हूँ...",
    send: "भेजें",
    settings: "सेटिंग्स",
    clearChat: "चैट साफ करें",
    changeLanguage: "भाषा",
    changeVoice: "आवाज",
    wakeWord: "वेक वर्ड",
    resetApp: "App रीसेट करें",
    close: "बंद",
    cancel: "रद्द करें",
    wakeWordHint: "यह बोलने पर मैं जाग जाऊंगा",
    welcomeMessage:
      "नमस्ते! 👋 मैं आपका खास दोस्त हूँ! किसी भी बात के बारे में बात करें.\n\n💡 आप कर सकते हैं:\n• गणित के सवाल पूछें\n• 'याद रखो कि...' बताएं\n• सिखाएं: 'जब मैं X बोलूं, तो Y बोलो'\n• समय या तारीख पूछें",
    voiceHint: "बोलने के लिए mic दबाएं",
    wakeWordNote:
      "⚡ APK install के बाद wake word काम करेगा। Expo Go में mic button इस्तेमाल करें।",
    confirmReset: "क्या आप sure हैं? सब मिट जाएगा।",
    yes: "हाँ, रीसेट करें",
    no: "नहीं",
  },
};

export function t(lang: Language, key: keyof (typeof strings)["en"]): string {
  const langStrings = strings[lang] as Record<string, string>;
  const enStrings = strings["en"] as Record<string, string>;
  return langStrings[key] ?? enStrings[key] ?? String(key);
}
