workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    environment:
      node: 18
      java: 17
    scripts:
      - name: Force Install pnpm & Dependencies
        script: |
          npm install -g pnpm@latest --force
          COREPACK_DISABLE=1 pnpm install
      - name: Expo Prebuild
        script: npx expo prebuild -p android --clean
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/**/*.apk
