workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    environment:
      node: 20
      java: 17
    scripts:
      - name: Force Clean
        script: |
          rm -rf android
      - name: Expo Prebuild
        script: |
          npx expo prebuild --platform android --clean
      - name: Build APK
        script: |
          cd android
          # इथे आपण पाथ फिक्स करण्यासाठी एक छोटी कमांड टाकत आहोत
          ./gradlew assembleRelease -Pandroid.injected.signing.store.file="" 
    artifacts:
      - android/app/build/outputs/apk/release/**/*.apk
      
