workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    environment:
      node: 20
      java: 17
    scripts:
      - name: Force Clean Everything
        script: |
          # हे कोडमॅजिकच्या कॅशला बायपास करून सर्व जुन्या फाइल्स उडवेल
          rm -rf node_modules
          rm -rf android
          npm install
      - name: Expo Prebuild
        script: |
          npx expo prebuild --platform android --clean
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/apk/release/**/*.apk
      
